services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USERNAME=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=magaludb
      - MYSQL_ROOT_PASSWORD=123